services:
  rabbitexporter:
    image: rabbitexporter_ocb
    build: ./rabbitexporter
    command: [ "--config=/etc/otelcol-config.yaml" ]
    volumes:
      - ./rabbitexporter/otel-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "8080:8080"
      - "13132:13132"

  rabbitreceiver:
    image: rabbitreceiver_ocb
    build: ./rabbitreceiver
    command: [ "--config=/etc/otelcol-config.yaml" ]
    volumes:
      - ./rabbitreceiver/otel-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "8080:8080"
      - "13132:13132"