dist:
  name: otelcol-custom
  description: Local OpenTelemetry Collector binary
  output_path: /tmp/dist
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.117.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.117.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.117.0
receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/rabbitmqreceiver v0.117.0
extensions:
    - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckv2extension v0.117.0