name: Pipeline

on:
  push:
    branches: ["main"]

env:
  IMAGE_REGISTRY: rg.fr-par.scw.cloud/otel-collector

jobs:
  tag:
    name: "Tag repo"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: conventional_changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.github_token }}
          skip-commit: true
    outputs:
      version: ${{ steps.conventional_changelog.outputs.version }}

  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # image represents the name of the image produced as well as the directory containing its Dockerfile
        image: [rabbitexorter]
    needs: tag
    steps:
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry: ${{ env.IMAGE_REGISTRY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./${{ matrix.image }}
          file: ./${{ matrix.image }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ matrix.image }}:latest
            ${{ env.IMAGE_REGISTRY }}/${{ matrix.image }}:${{ needs.tag.outputs.version }}
